version: 2
permissions:
  contents: write
  issues: write
  pull-requests: write
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Madrid"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Madrid"
